project:
  type: "website"

website:
  title: "CNG 2025 - GeoJupyter"
  site-url: "https://mfisher87.github.io/presentation-cng2025"

  repo-url: &repo-url "https://github.com/mfisher87/presentation-cng2025"
  repo-actions: ["edit", "issue"]

  navbar:
    left:
      - text: "Slides"
        href: "slides.qmd"

format:
  html:
    from: "markdown+emoji"
    theme:
      - "cosmo"
      - "brand"
    css: "assets/css/main.css"
    toc: true
