project:
  type: "website"

website:
  title: "CNG 2025 - GeoJupyter"
  navbar:
    left:
      - text: "Slides"
        href: "slides.md"

format:
  html:
    theme:
      - "cosmo"
      - "brand"
    css: "styles.css"
    toc: true
