[project]
authors = ["Matt Fisher <mfisher87@gmail.com>"]
channels = ["conda-forge"]
name = "presentation-cng2025"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
preview = "quarto preview"
render = "quarto render"

[dependencies]
quarto = ">=1.6.43,<2"
